--- 
  - name: Update apt-cache
    apt: update_cache=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install build tools
    apt:
        name: ['gcc', 'g++', 'make', 'build-essential', 'git', 'autoconf', 'curl', 'libtool', 'libssl-dev', 'libcurl4-openssl-dev', 'libz-dev']
        state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install build tools
    apt:
        name: ['gcc', 'g++', 'make', 'build-essential', 'git', 'autoconf', 'curl', 'libtool', 'libssl-dev', 'libcurl4-openssl-dev', 'libz-dev']
        state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Install libtool-bin
    apt:
      name: libtool-bin
      state: latest
    when: ansible_distribution == 'Debian'
    ignore_errors: yes

  - name: make source directory writeable
    file: path=/usr/local/src state=directory mode=0777

  - name: check out sipp 
    git: repo=https://github.com/SIPp/sipp.git
          dest=/usr/local/src/sipp
          version={{sippVersion}}
          depth=50
          accept_hostkey=yes
          force=yes
    become: no

  - name: build sipp
    shell: ./build.sh  --with-rtpstream --with-pcap && make install
    become: yes
    args:
      executable: /bin/bash
      chdir: /usr/local/src/sipp/
      creates: /usr/local/bin/sipp

